### ISSUE TITLE
Backoff parameter instead of simple time.Duration

### ISSUE THREAD

**Issue by cristaloleg** [cristalhq/hedgedhttp#28]
```
// Backoff logic for hedged requests.
type Backoff interface {
	// Next returns a time to wait before next request and flag to stop.
	Next() (next time.Duration, stop bool)
}
```

Probably interface might be too heavy for this and just a `func() (time.Duration, bool)` should be enough. This is kinda relates to https://github.com/golang/go/issues/47487 (CC: https://github.com/cristalhq/acmd/issues/7) but 6 months to wait at least.

**Comment by cristaloleg** [comment]
Kindly ping @cyriltovena @annanay25 you are the biggest user for now, curious do you have an opinion on that?

Note: default behaviour will be the same as before (default `Backoff` strategy will be just a const timeout), but there will be additional knob to make timeout much flexible.

Also, I'm okay to update loki & tempo to the new api.

**Comment by cyriltovena** [comment]
Sounds good you should provide helper for previous compatibility

**Comment by cristaloleg** [comment]
Yes, there will be default backoff with the same behaviour as before. So, if it sounds ok for you - will make a PR and we will see. Thanks for the response.

**Comment by cristaloleg** [comment]
Forgot to share: well, sadly this feature is more complicated than I've imagined in the beginning. Because for every new request that we're going to hedge we need a new backoff mechanism user should provide `BackoffFactory`:

```go
// BackoffFactory creates new backoff
type BackoffFactory interface {
    NewBackoff() Backoff
}

// Backoff logic for hedged requests.
type Backoff interface {
	// Next returns a time to wait before next request and flag to stop.
	Next() (next time.Duration, stop bool)
}
```

I don't see much reason to add this at the current stage and I'm totally unsure that someone needs such delay granularity. Closing as "won't do" because feature solves to little things.
