### ISSUE TITLE
Flaky test: TestHedgedResponseWins

### ISSUE THREAD

**Issue by gibmat** [cristalhq/hedgedhttp#47]
I've packaged this library for Debian, as a dependency of other packages, and have noticed that there is a test that seems to be flaky across multiple builds/autopkgtests for the latest release (0.8.0):

```
=== RUN   TestHedgedResponseWins
    hedged_test.go:363: Unnexpected actualRoundTrips: 4
--- FAIL: TestHedgedResponseWins (0.60s)
```

(See https://buildd.debian.org/status/fetch.php?pkg=golang-github-cristalhq-hedgedhttp&arch=all&ver=0.8.0-1&stamp=1692386052&raw=0, https://ci.debian.net/data/autopkgtest/testing/ppc64el/g/golang-github-cristalhq-hedgedhttp/36961327/log.gz, https://ci.debian.net/data/autopkgtest/testing/i386/g/golang-github-cristalhq-hedgedhttp/36953254/log.gz)

**Comment by cristaloleg** [comment]
Oh, interesting! First sorry for the failed build. Second: I saw this failure once and was sure was this a dream or not. I will take a closer look today-tomorrow.

Thanks for the report!

**Comment by cristaloleg** [comment]
Fix is available in https://github.com/cristalhq/hedgedhttp/releases/tag/v0.8.1

**Comment by gibmat** [comment]
Awesome, thanks for the quick fix!
